### ISSUE TITLE
It doesn't work in Mac OS X Lion, can't find Tor executable

### ISSUE THREAD

**Issue by rafmagana** [jtorchat/jtorchat-old#2]
Here's the log

```
[1:54:00 - Config] Using /Users/raf/Downloads/jtorchat 0.7.7/jtorchat/ as BASE_DIR
[1:54:00 - Config] Using /Users/raf/Downloads/jtorchat 0.7.7/jtorchat/data/config/ as CONFIG_DIR
[1:54:00 - Config] Using /Users/raf/Downloads/jtorchat 0.7.7/jtorchat/data/downloads/ as DOWNLOAD_DIR
[1:54:00 - Config] Using /Users/raf/Downloads/jtorchat 0.7.7/jtorchat/data/log/ as LOG_DIR
[1:54:00 - Config] Using /Users/raf/Downloads/jtorchat 0.7.7/jtorchat/data/offlinemsgs/ as MESSAGE_DIR
[1:54:00 - Config] Using /Users/raf/Downloads/jtorchat 0.7.7/jtorchat/data/page/ as PAGE_DIR
[1:54:00 - Config] Using /Users/raf/Downloads/jtorchat 0.7.7/jtorchat/data/Tor/ as TOR_DIR
[1:54:00 - Config] Using /Users/raf/Downloads/jtorchat 0.7.7/jtorchat/data/lang/ as LANG_DIR
[1:54:00 - Config] ourId not defined using null
[1:54:00 - Config] profile_name not defined using null
[1:54:00 - Config] profile_text not defined using null
[1:54:00 - Config] lang not defined using en
[1:54:00 - Config] alert not defined using 1
[1:54:00 - Config] loadPortableTor not defined using 1
[1:54:00 - Config] pageactive not defined using 0
[1:54:00 - Config] transferonstart not defined using 0
[1:54:00 - Config] obfsproxy not defined using 0
[1:54:00 - Config] ClickableLinks not defined using 0
[1:54:00 - Config] offlineMod not defined using 0
[1:54:00 - Config] image_size not defined using 16
[1:54:00 - Config] icon_size not defined using 16
[1:54:00 - Config] icon_space not defined using 2
[1:54:00 - Config] ICON not defined using orginal
[1:54:00 - Config] Using /Users/raf/Downloads/jtorchat 0.7.7/jtorchat/data/icon/orginal as ICON_DIR
[1:54:00 - Config] Using 11158 as socks port and 8976 as local port.
[1:54:00 - ThreadManager] Starting Tor.
[1:54:00 - TorLoader ] Checking OS: mac os x
[1:54:00 - TorLoader] Can't detect OS type, using system tor (need system tor to work)
/Users/raf/Downloads/jtorchat 0.7.7/jtorchat/data/Tor
[1:54:00 - TorLoader] Cannot run program "tor" (in directory "/Users/raf/Downloads/jtorchat 0.7.7/jtorchat/data/Tor"):            error=2, No such file or directory
      java.lang.Exception: Stack trace
      at java.lang.Thread.dumpStack(Thread.java:1273)
at net.tsu.TCPort.Logger.log(Logger.java:74)
at net.tsu.TCPort.TorLoader$1.run(TorLoader.java:168)
at net.tsu.TCPort.ThreadManager$1.run(ThreadManager.java:24)
at java.lang.Thread.run(Thread.java:680)
```

Here's the output of java -version

```
java version "1.6.0_31"
Java(TM) SE Runtime Environment (build 1.6.0_31-b04-413-11M3623)
Java HotSpot(TM) 64-Bit Server VM (build 20.6-b01-413, mixed mode)
```

**Comment by jtorchat** [comment]
There is no executable for mac (we have not finish the starter)
But you can start it when you use your own tor on the right ports:
[1:54:00 - Config] Using 11158 as socks port and 8976 as local port.
And go to the Config in data/config/settings.ini and change loadPortableTor to 0
The problem is we have no mac system to test it for portable start.

**Comment by zerotamaitsu** [comment]
rafmagana do you know how to get just the tor binaries for mac by itself?

**Comment by zerotamaitsu** [comment]
rafmagana 

Also if you really want it to work at the moment, you can try manually installing tor, and adding a PATH to the "tor" executable.

**Comment by rafmagana** [comment]
@zerotamaitsu I don't know :(

I'm using [Vidalia](https://www.torproject.org/projects/vidalia.html.en), I will check out about adding a PATH to the tor executable, thanks.

**Comment by zerotamaitsu** [comment]
let us know if it works. It was added as a contingency (when linux wasn't supported natively) a few versions ago... but lots has changed, and it hasn't been tested since.

**Comment by burdges** [comment]
There is a tor executable at /Applications/TorBrowser_en-US.app/Contents/MacOS/tor on my install, but you cannot depend upon that path under Mac OS X.  If you like, I could find script to locate tor via the Tor browser bundle, starting Vidalia if necessary.  I presume the tor daemon itself should always be started by Vidalia, not TorChat, otherwise it'll never receive the bridge configuration for ISPs that censor Tor.
